DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS contacts_backup;

CREATE TABLE contacts (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR NOT NULL,
	last_name VARCHAR NOT NULL,
	email VARCHAR NOT NULL UNIQUE
);

INSERT INTO contacts (first_name, last_name, email)
VALUES
	('John','Doe','john.doe@postgresqltutorial.com'),
    ('David','William','david.william@postgresqltutorial.com')
RETURNING *;

CREATE TABLE contacts_backup
AS TABLE contacts;

ALTER TABLE contacts_backup ADD PRIMARY KEY (id);
ALTER TABLE contacts_backup ADD UNIQUE (email);
ALTER TABLE contacts_backup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT * FROM contacts_backup;